apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
  namespace: {{.Values.metadata.turbo_namespace}}
spec:
  global:
    storageClassName: {{.Values.metadata.storageClassName}}
    customImageNames: false
    repository: registry.connect.redhat.com/turbonomic
    tag: {{.Values.metadata.tag}}
  nginx:
    nginxIsPrimaryIngress: false
    httpsRedirect: false
  nginxingress:
    enabled: false
  openshiftingress:
    enabled: true
  db:
    persistence:
      size: 50Gi
  instana:
    enabled: true
  kubeturbo:
    enabled: true
