apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: argocd
  name: turbonomic
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  finalizers:
  - kubernetes
