apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: turbonomic-mkk5d
  namespace: {{.Values.metadata.turbo_namespace}}
spec:
  targetNamespaces:
  - {{.Values.metadata.turbo_namespace}}
  
