apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Xl.v1.charts.helm.k8s.io
  name: turbonomic-mkk5d
  namespace: {{.Values.metadata.turbo_namespace}}
spec:
  targetNamespaces:
  - {{.Values.metadata.turbo_namespace}}
  
