apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: t8c-certified
  namespace: {{.Values.metadata.turbo_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: t8c-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace

