apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: xl-release
  namespace: {{ .Release.Namespace }}

spec:
  global:
    {{- if .Values.metadata.storageClassName }}
    storageClassName: {{.Values.metadata.storageClassName}}
    {{- end }}
    customImageNames: false
    repository: registry.connect.redhat.com/turbonomic
    tag: {{.Values.metadata.tag}}
  nginx:
    nginxIsPrimaryIngress: false
    httpsRedirect: false
  nginxingress:
    enabled: false
  openshiftingress:
    enabled: true
 {{- if .Values.metadata.db_persistence_size }}
  db:
    persistence:
      size: {{.Values.metadata.db_persistence_size}}
  {{- end }}
  instana:
    enabled: {{.Values.metadata.instana_enable}}
  kubeturbo:
    enabled: {{.Values.metadata.kubeturbo_enable}}

