{{- if .Values.metadata.administrator_password }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  generateName: config-administrator-password-
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: set-password
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "username=administrator"
          - "--data-urlencode"
          - "password={{ .Values.metadata.administrator_password }}"
          - "http://api:8080/api/v3/initAdmin"
          - "--retry"
          - "15"
          - "--retry-max-time"
          - "500"
           
      restartPolicy: Never
  backoffLimit: 2
{{- end }}



